### ISSUE TITLE
Rails 5.1.2 support !

### ISSUE THREAD

**Issue by kesha-antonov** [anycable/anycable-rails#11]
Hello @palkan !
I want to try this awesome lib but it is not compatible with rails 5.1.2 
Can you update it?

https://github.com/anycable/anycable-rails/blob/master/lib/anycable/rails/actioncable/connection.rb
https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/base.rb

I guess here we have some inconsistency, right?

**Comment by kesha-antonov** [comment]
![screen shot 2017-07-31 at 19 25 34](https://user-images.githubusercontent.com/11584712/28787977-1fa11350-7627-11e7-9a8e-bd4511745122.png)

**Comment by kesha-antonov** [comment]
Or maybe I'm doing something wrong? I see you use Rails 5.1.2 here: https://github.com/anycable/anycable_demo/blob/master/Gemfile.lock

**Comment by palkan** [comment]
Hi, @kesha-antonov!

Looks like you're trying to connect to built-in Action Cable server and not AnyCable one. But `anycable-rails`, which (unfortunately) monkey-patches `ActionCable::Connection` is loaded.

1) Ensure that your JS (or whatever) client connects to AnyCable websocket server (i guess, `anycable-go`).

2) Do you set `config.action_cable.mount_path` manually in your `<environment>.rb` or `application.rb`?

**Comment by kesha-antonov** [comment]
Thanks for the answer! @palkan 

My configs are:

1) development.rb: ```config.action_cable.url = "ws://127.0.0.1:3334/cable"```
2) anycable.yml: 
```
development:
  # gRPC server host
  rpc_host: "127.0.0.1:50051"
  # Redis URL (for broadcasting)
  redis_url: "redis://127.0.0.1:6379"
  # Redis channel name
  redis_channel: "anycable"


production:
  # gRPC server host
  rpc_host: "127.0.0.1:50051"
  # Redis URL (for broadcasting)
  redis_url: "redis://127.0.0.1:6379"
  # Redis channel name
  redis_channel: "anycable"
```
3) gem 'anycable-rails', '~> 0.4.6'
4) ./bin/anycable
5) anycable-go -rpc=127.0.01:50051 -redis=redis://localhost:6379 -redis_channel=anycable -addr=127.0.01:3334 -log
