### ISSUE TITLE
undefined method loaded? for Hash

### ISSUE THREAD

**Issue by danieldocki** [anycable/anycable-rails#129]
### Tell us about your environment

**Ruby version:**
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]

**Rails version:**
Rails 6.0.3.1

**`anycable` gem version:**
1.0.0rc1

**`anycable-rails` gem version:**
1.0.0rc1

**`grpc` gem version:**
1.28.0

### What did you do?
I'm trying to set up AnyCable in development with Devise.

### What did you expect to happen?
I hope to identify the user and the customer

### What actually happened?
```
14:00:33 anycable.1 | [AnyCable sid=6C2oHz0RvMFcqOxOblw5n] Warden customer : #<Customer:0x00007ffe93d05c98>
14:00:33 anycable.1 | [AnyCable sid=6C2oHz0RvMFcqOxOblw5n] undefined method `loaded?' for #<Hash:0x00007ffe95426940>

```

`connection.rb`
```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user, :current_customer

    def connect
      env['rack.session'] = cookies.encrypted[:_app_session]

      if Warden::SessionSerializer.new(env).fetch(:store_customer)
        self.current_customer = find_verified_customer
        logger.add_tags 'ActionCable', current_customer.name
      end

      if Warden::SessionSerializer.new(env).fetch(:user)
        self.current_user = find_verified_user
        logger.add_tags 'ActionCable', current_user.name
      end
    end

    private

    def find_verified_user
      if verified_user = Warden::SessionSerializer.new(env).fetch(:user)
        verified_user
      else
        reject_unauthorized_connection
      end
    end

    def find_verified_customer
      if verified_user = Warden::SessionSerializer.new(env).fetch(:store_customer)
        verified_user
      else
        reject_unauthorized_connection
      end
    end
  end
end
```

`anycable.yml`
```yml
default: &default
  access_logs_disabled: false
  persistent_session_enabled: true
  rpc_host: "127.0.0.1:50051"
  log_grpc: false
  broadcast_adapter: redis
  redis_channel: "__anycable__"

development:
  <<: *default
  redis_url: "redis://localhost:6379/1"

production:
  <<: *default
```

`cable.yml`
```yml
development:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

test:
  adapter: test

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
```

`Procfile.dev`
```
server: bin/rails server
worker: bundle exec sidekiq -C ./config/sidekiq.yml
assets: bin/webpack-dev-server
anycable: bundle exec anycable --server-command "anycable-go --host=ws.work.glabs --port 3334"
```

`development.rb`
```ruby
  config.action_cable.url = 'ws://ws.work.glabs:3334/cable'
  config.action_cable.disable_request_forgery_protection = true

  if Rails.root.join('tmp', 'caching-dev.txt').exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = {
      'Cache-Control' => "public, max-age=#{2.days.to_i}"
    }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :redis_cache_store
  end
``
