### ISSUE TITLE
can't run bundle exec anycable 

### ISSUE THREAD

**Issue by xxSkyy** [anycable/anycable-rails#161]
I've got problem running `bundle exec anycable` command. I followed instructions without problems despite #160 , and I get error
```
 ✗ bundle exec anycable                      
Starting AnyCable RPC server (pid: 26391)
AnyCable version: 1.1.1 (proto_version: v1)
Serving Rails application from ./config/environment.rb
AnyCable server builder must be configured. Make sure you've required a gem (e.g. `grpc`) or configured `AnyCable.server_builder` yourself
```

I did install `bundle exec rails g anycable:setup`

cable.yml
```yml
development:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

test:
  adapter: test

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
```

development.rb
```rb
require 'active_support/core_ext/integer/time'

Rails.application.configure do
  # Specify AnyCable WebSocket server URL to use by JS client
  config.after_initialize do
    if AnyCable::Rails.enabled?
      config.action_cable.url = ActionCable.server.config.url = ENV.fetch('CABLE_URL',
                                                                          'ws://localhost:3030/cable')
    end
  end
```

anycable.yml
```yml
default: &default
  # Turn on/off access logs ("Started..." and "Finished...")
  access_logs_disabled: false
  # Persist "dirty" session between RPC calls (might be required for apps using stimulus_reflex <3.0)
  # persistent_session_enabled: true
  # This is the host and the port to run AnyCable RPC server on.
  # You must configure your WebSocket server to connect to it, e.g.:
  #   $ anycable-go --rpc-host="<rpc hostname>:50051"
  rpc_host: "127.0.0.1:50051"
  # Whether to enable gRPC level logging or not
  log_grpc: false
  # Use Redis to broadcast messages to AnyCable server
  broadcast_adapter: redis
  # Use the same channel name for WebSocket server, e.g.:
  #   $ anycable-go --redis-channel="__anycable__"
  redis_channel: "__anycable__"
  # You can use REDIS_URL env var to configure Redis URL.
  # Localhost is used by default.
  # redis_url: "redis://localhost:6379/1"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```

setting RAILS_ENC=development doesn't help

### Tell us about your environment

**Ruby version:** 2.7.2

**Rails version:** 6.1.4

**`anycable` gem version:**  1.1

**`anycable-rails` gem version:** 1.1.2

**`grpc` gem version:** 1.38.0-universal-darwin
