### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/cable"):

### ISSUE THREAD

**Issue by phiele** [anycable/anycable-rails#194]
**EDIT: Locally everything seems to be working now, besides getting this error:**
```
09:02:58 ws.1      | 2024/02/21 09:02:58 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
```
**However, in production the connection still keeps failing.**

<br>

Environment:
- **ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]**
- **Rails 7.0.6**
- **`anycable` gem version: 1.4.3**
- **RPC-less with JWT authentication and speedy streams**
- **Host: Digital Ocean**
- **Docker image for anycable-go websocket: [anycable/anycable-go:1.4.8](https://hub.docker.com/layers/anycable/anycable-go/1.4.8/images/sha256-b450fb3bfc64b4a85354b86631a91fe01d2a61c881e3406db63c0cec18d6e663?context=explore)**

<br>

I followed every step of the [Exploring Rails 7, Hotwire and AnyCable speedy streams](https://anycable.io/blog/anycasts-rails-7-hotwire-and-anycable/) tutorial and already went through the documented [troubleshooting](https://docs.anycable.io/troubleshooting?id=troubleshooting-%f0%9f%94%a5), but somehow the Client connection still keeps failing in production.

**1) config.action_cable.url points to the AnyCable server and not to the Rails one.**
```
irb(main):001:0> Rails.application.config.action_cable.url
=> "wss://dev.tech/cable"
irb(main):001:0> ActionCable.server.config.url
=> "wss://dev.tech/cable"
```

**2) Make sure that action_cable_meta_tag is called before JS script is loaded.**
```
<head>
    <title>AnyCable app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_with_jwt_meta_tag %> <%# Required for AnyCable %>
    <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
```
  
here's the actual DOM element:
```
<meta name="action-cable-url" content="wss://dev.tech/cable?jid=eyJhbGciOiJIUzI1NiJ9.eyJleHQiOiJ7fSIsImV4cCI6MTcwODUwNjA5Mn0.8C4W0akHvPjiOhh67hOg_fQSNtkMATi_boAzKo2tEpo">
```

**3) Make sure you do not pass incorrect URL to JS createConsumer question.**
- createConsumer is not imported

**4)  In case of using a reverse proxy (e.g. Nginx), check that it points to the correct server as well.**
- no reverse proxy

<br>

For the sake of completeness:
*anycable.yml*
```
default: &default
  # Turn on/off access logs ("Started..." and "Finished...")
  access_logs_disabled: false
  # Whether to enable gRPC level logging or not
  log_grpc: false
  # Use Redis to broadcast messages to AnyCable server
  broadcast_adapter: redis
  # Use the same channel name for WebSocket server, e.g.:
  #   $ anycable-go --redis_channel="__anycable__"
  redis_channel: "__anycable__"
  # You can use REDIS_URL env var to configure Redis URL.
  # Localhost is used by default.
  # redis_url: "redis://localhost:6379/1"
  jwt_id_key: "secret"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  redis_url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/1") %>
```

*cable.yml*
```
development:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

test:
  adapter: test

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
```
  
*production.rb*
```
Rails.application.configure do
  # Specify AnyCable WebSocket server URL to use by JS client
  config.after_initialize do
    config.action_cable.url = ActionCable.server.config.url = ENV.fetch("CABLE_URL", "/cable") if AnyCable::Rails.enabled?
  end

  # Specify AnyCable Turbo Streams verifier key
  # config.turbo.signed_stream_verifier_key = ENV.fetch("ANYCABLE_TURBO_RAILS_KEY")
  config.turbo.signed_stream_verifier_key = "secret"
  ...
  ``` 
  
*Environment variables:*
```
REDIS_URL=rediss://default:secret@dev-app-redis-do-user-123456789-0.b.db.ondigitalocean.com:25061
CABLE_URL=wss://dev.tech/cable
ANYCABLE_HOST=0.0.0.0
ANYCABLE_JWT_ID_KEY=secret
ANYCABLE_TURBO_RAILS_KEY=secret
ACTION_CABLE_ADAPTER=any_cable
``` 

*Logs:*
```
[dev] [2024-02-21 08:00:55] => Booting Puma
[dev] [2024-02-21 08:00:55] => Rails 7.0.6 application starting in production 
[dev] [2024-02-21 08:00:55] => Run `bin/rails server --help` for more startup options
[dev] [2024-02-21 08:00:59] 
[dev] [2024-02-21 08:00:59] ⚡ Motor::Admin is starting under /motor_admin
[dev] [2024-02-21 08:00:59] 
[dev] [2024-02-21 08:00:59] Puma starting in single mode...
[dev] [2024-02-21 08:00:59] * Puma version: 5.6.6 (ruby 3.2.2-p53) ("Birdie's Version")
[dev] [2024-02-21 08:00:59] *  Min threads: 5
[dev] [2024-02-21 08:00:59] *  Max threads: 5
[dev] [2024-02-21 08:00:59] *  Environment: production
[dev] [2024-02-21 08:00:59] *          PID: 1
[dev] [2024-02-21 08:00:59] * Listening on http://0.0.0.0:3000
[dev] [2024-02-21 08:00:59] Use Ctrl-C to stop
[dev] [2024-02-21 08:01:26] I, [2024-02-21T09:01:26.929148 #1]  INFO -- : [2d9528bf-eac6-4c61-91eb-96bc7919f93e] Started GET "/cable?jid=eyJhbGciOiJIUzI1NiJ9.eyJleHQiOiJ7fSIsImV4cCI6MTcwODQ3MjkyM30.yJPBccjVnlFRUXwYJ_WyRWnNynCfJoOhPUZDeNKot9I" for 162.158.112.130 at 2024-02-21 09:01:26 +0100
[dev] [2024-02-21 08:01:26] F, [2024-02-21T09:01:26.941229 #1] FATAL -- : [2d9528bf-eac6-4c61-91eb-96bc7919f93e]   
[dev] [2024-02-21 08:01:26] [2d9528bf-eac6-4c61-91eb-96bc7919f93e] ActionController::RoutingError (No route matches [GET] "/cable"):
[dev] [2024-02-21 08:01:26] [2d9528bf-eac6-4c61-91eb-96bc7919f93e]   
[dev] [2024-02-21 08:01:26] I, [2024-02-21T09:01:26.943861 #1]  INFO -- : [2d9528bf-eac6-4c61-91eb-96bc7919f93e] Processing by ErrorsController#not_found as */*
[dev] [2024-02-21 08:01:26] I, [2024-02-21T09:01:26.943978 #1]  INFO -- : [2d9528bf-eac6-4c61-91eb-96bc7919f93e]   Parameters: {"jid"=>"eyJhbGciOiJIUzI1NiJ9.eyJleHQiOiJ7fSIsImV4cCI6MTcwODQ3MjkyM30.yJPBccjVnlFRUXwYJ_WyRWnNynCfJoOhPUZDeNKot9I"}
[dev] [2024-02-21 08:01:27] I, [2024-02-21T09:01:27.311280 #1]  INFO -- : [17045664-5ff9-4da8-acc6-e3498f2c580a] Started GET "/cable?jid=eyJhbGciOiJIUzI1NiJ9.eyJleHQiOiJ7fSIsImV4cCI6MTcwODUwNjAxN30.6-c-0L9lDIsedgCEei1c96xKygcJkL_TeFDp3oT7b5E" for 162.158.112.130 at 2024-02-21 09:01:27 +0100
[dev] [2024-02-21 08:01:27] F, [2024-02-21T09:01:27.413998 #1] FATAL -- : [17045664-5ff9-4da8-acc6-e3498f2c580a
``` 

*Logs websocket:*
```
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.069Z context=main Starting AnyCable 1.4.8-f9dd29c (pid: 1, open file limit: 1048576, gomaxprocs: 8)
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.069Z context=main JWT identification is enabled (param: jid, enforced: false)
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.069Z context=main Using channels router: Turbo::StreamsChannel
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.070Z context=main Anonymized telemetry is on. Learn more: https://docs.anycable.io/anycable-go/telemetry
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.070Z context=main Using no-op (legacy) broker
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.073Z context=rpc RPC controller initialized: localhost:50051 (concurrency: 28, impl: grpc, enable_tls: false, proto_versions: v1)
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.073Z context=main Handle WebSocket connections at http://0.0.0.0:8080/cable
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.073Z context=main Handle health requests at http://0.0.0.0:8080/health
[2024-02-21 08:00:26] I 2024-02-21T08:00:26.149Z context=broadcast provider=redis Subscribed to Redis channel: __anycable__
[2024-02-21 08:00:26] 
```

<br>

Unfortunately, the other [closed issues](https://github.com/anycable/anycable-rails/issues?q=is%3Aissue+is%3Aclosed+RoutingError) relating to the same problem haven't helped either. 

Any clue what else I could try to debug?
